spring:
  application:
    name: CarsBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

server:
  port: ${PORT}